import operator
from typing import Annotated, Any, Literal, NotRequired

from langchain_core.messages import BaseMessage
from typing_extensions import TypedDict

IntentType = Literal["greeting", "question", "request", "fallback"]
JourneyState = Literal["E0", "E1", "E2a", "E2b", "E3", "E4", "E5", "E6"]
LeadProfile = Literal["investidor", "proprietario", "fora_de_escopo", "unknown"]
LeadScore = Literal["A", "B", "C", "D"]


class AgentState(TypedDict):
    messages: Annotated[list[BaseMessage], operator.add]
    resume_context: NotRequired[str]
    latest_user_message: NotRequired[str]
    intent: NotRequired[IntentType]
    intent_reason: NotRequired[str]
    profile: NotRequired[LeadProfile]
    journey_state: NotRequired[JourneyState]
    score: NotRequired[LeadScore]
    disposition: NotRequired[str]
    out_of_scope_reason: NotRequired[str]
    handoff_reason: NotRequired[str]
    compliance_violation: NotRequired[str]
    lead_contact_gap: NotRequired[int]
    lead_name: NotRequired[str]
    lead_origin: NotRequired[str]
    journey_status: NotRequired[str]
    requires_specialist: NotRequired[bool]
    specialist_name: NotRequired[str | None]
    specialist_reason: NotRequired[str | None]
    specialist_status: NotRequired[str | None]
    specialist_result: NotRequired[dict[str, Any] | None]
    motivacao: NotRequired[str]
    estagio_decisao: NotRequired[str]
    capital_faixa: NotRequired[str]
    origem_recurso: NotRequired[str]
    horizonte: NotRequired[str]
    horizonte_decisao: NotRequired[str]
    pf_pj: NotRequired[str]
    homologada: NotRequired[bool | None]
    exclusividade: NotRequired[bool | None]
    concessionaria: NotRequired[str]
    cidade_uf: NotRequired[str]
    potencia_kwp: NotRequired[float | int | None]
    data_operacao: NotRequired[str]
    capacidade_ociosa_pct: NotRequired[float | int | None]
    handoff_package: NotRequired[str]
    transition_reason: NotRequired[str]
    journey_transitions: NotRequired[list[dict[str, str]]]
    response_text: NotRequired[str]
    response_media: NotRequired[list[dict[str, Any]]]
    response_audio: NotRequired[dict[str, Any] | None]
    status: NotRequired[str]
